## interpreter directive - this is a shell script
#!/bin/sh
#
## ask PBS for time (format hh:mm:ss)
#PBS -l walltime=24:00:00
#
## ask for one node with 1 cpus and total 1gb memory (per node)
#PBS -l select=1:ncpus=4:mem=8GB
#PBS -J 0-1399

## the number of subjobs in queue
#
#
##load application module
module load gcc/8.2.0
module load anaconda3/personal
#
##file management - Copy input file to TMPDIR
echo $TMPDIR

cp $WORK/Tip_Writing_Simulations/ScanangleVsUnifrom/disk.$PBS_ARRAY_INDEX.mif $TMPDIR
cp $WORK/Tip_Writing_Simulations/test/100nm.config $TMPDIR
cp $WORK/Tip_Writing_Simulations/test/pmmovie.py $TMPDIR


mkdir -p $WORK/Tip_Writing_Simulations/ScanangleVsUnifrom/Results/$PBS_ARRAY_INDEX
ls
echo
#
##command line
echo RunningCode

tclsh $WORK/oommf/oommf.tcl boxsi disk.$PBS_ARRAY_INDEX.mif

echo FinishedCode
#
##file management - Move output files to WORK directory

ls
echo CopiedFiles
cp -a * $WORK/Tip_Writing_Simulations/ScanangleVsUnifrom/Results/$PBS_ARRAY_INDEX
## Diagnostics
#
echo ------------------------------------------------------------------------------------------------------------------
ls -la /tmp/
nvidia-smi
#